//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosWS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automovil
    {
        public System.Guid Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Año_fabricacion { get; set; }
        public string Precio { get; set; }
        public string Combustible { get; set; }
    }
}
